import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#111d2b',
        'tertiary-fixed': '#a855f7',
        'on-primary-fixed': '#000000',
        'inverse-on-surface': '#455060',
        'outline': '#5a6a84',
        'primary': '#8b5cf6',
        'on-surface': '#eef2f6',
        'surface-container-high': '#0f172a',
        'on-primary': '#1e1b4b',
        'on-error': '#490013',
        'surface-dim': '#040914',
        'surface-container-lowest': '#000000',
        'inverse-primary': '#4f46e5',
        'secondary': '#818cf8',
        'surface': '#0d101a',
        'surface-container': '#131826',
        'primary-fixed': '#c7d2fe',
        'tertiary': '#d8b4fe',
        'on-surface-variant': '#9caec2',
        'error-dim': '#f43f5e',
        'on-secondary-container': '#e0e7ff',
        'on-error-container': '#ffb2b9',
        'background': '#0d101a',
        'surface-container-highest': '#1c2436',
        'tertiary-container': '#7e22ce',
        'outline-variant': '#334155',
        'secondary-fixed': '#c7d2fe',
        'error': '#ef4444',
        'on-primary-fixed-variant': '#312e81',
        'primary-dim': '#a78bfa',
        'on-tertiary-fixed': '#2e1065',
        'secondary-fixed-dim': '#b1beff',
        'tertiary-dim': '#a855f7',
        'primary-container': '#4c1d95',
        'primary-fixed-dim': '#818cf8',
        'on-background': '#eef2f6',
        'surface-bright': '#242d3d',
        'on-secondary': '#1e1b4b',
        'on-tertiary': '#2e1065',
        'inverse-surface': '#f8fafc',
        'on-tertiary-container': '#f3e8ff',
        'on-primary-container': '#ede9fe',
        'secondary-container': '#312e81',
        'surface-tint': '#8b5cf6',
        'on-tertiary-fixed-variant': '#6b21a8',
        'on-secondary-fixed': '#312e81',
        'error-container': '#7f1d1d',
        'surface-container-low': '#111726',
        'on-secondary-fixed-variant': '#4338ca',
        'tertiary-fixed-dim': '#a855f7',
      },
      fontFamily: {
        'headline': ['Manrope'],
        'body': ['Inter'],
        'label': ['Inter'],
      },
    },
  },
  plugins: [],
} satisfies Config
